name: Build themes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    name: Build Themes
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Set up icnspack
      run: |
        wget "https://github.com/acidanthera/OpenCorePkg/releases/download/0.9.3/OpenCore-0.9.3-RELEASE.zip"
        unzip OpenCore-0.9.3-RELEASE.zip
        mv Utilities/icnspack/icnspack Utilities/icnspack/icnspack.mac
        mv Utilities/icnspack/icnspack.linux Utilities/icnspack/icnspack
    - run: |
        echo "$GITHUB_WORKSPACE/Utilities/icnspack" >> $GITHUB_PATH
    - name: Build themes
      run: |
        python buildthemes.py
    - name: Upload Themes
      uses: softprops/action-gh-release@v1
      with:
        files: Themes.zip
        tag_name: ${{ github.event.head_commit.url }}
